theme: jekyll-theme-slate
title: MQTT2GO Convention
description: An agreement on positions, definitions and specifications for the use of MQTT in harmonised form for service platforms, IoT devices, control nodes and user applications.
